clas12_plugins += [{
    'name'                : 'dc',
    'sources'             : files('readoutSpecs.cc', 'process_gtouchable.cc', 'calibration_constants.cc',
                                   'load_tt.cc', 'digitize_hit.cc'),
    'dependencies'        : [gemc_dep, ccdb_dep],
    'include_directories' : [include_directories('.')],
}]
