"""LTCC native-volume geometry, ported from clas12Tags geometry_source/ltcc.

Ported perl scripts: ltccBox.pl (sector boolean mother), cyl_mirrors.pl,
hyp_mirrors.pl, ell_mirrors.pl, pmts.pl, shields.pl. All shape parameters come
from `ltcc__parameters_default.txt`, generated by `root -q -b mirrors.C`
(see ltcc_parameters.py).

The CAD mesh sources are rows in the same `ltcc` SQLite system as the native
geometry. Their placement is authored in `stls/cad__default.yaml` and uploaded
by the gcad feature (see ltcc.py); the remaining frame and Winston-cone
placements are generated here as `copyOf` volumes. The STL meshes are built by
`build_cad_meshes.py`. The ltcc_AlMgF2 optical surface (mirrors.pl) is recorded
on every native mirror and source/copied Winston cone through `GVolume.mirror`.

Numeric values computed in perl are formatted with perl's default `%.15g`
stringification (`fstr`) so the output matches the clas12Tags references exactly;
values read from the parameters file are passed through as raw strings, as the
perl scripts interpolate them verbatim.
"""

import math

from pygemc import GVolume

from ltcc_parameters import load_parameters


NMIRRORS = 18  # mirrors per sector side; also the "nmirrors" parameter
SECTORS = (1, 2, 3, 4, 5, 6)

# All six sector gas mothers are identical (see build_ltcc_box). The CAD meshes are sourced from sector 3
# and reused in the other sectors with copyOf placements; the shared mother is sized to contain them.

# sectors 1..6 presence and gas material per configuration (from ltcc.pl)
SECTOR_CONFIG = {
    "default": ((1, 1, 1, 1, 1, 1), ("C4F10",) * 6),
    "rga_spring2018": ((0, 1, 1, 0, 1, 1), ("na", "N2", "N2", "na", "C4F10", "N2")),
    "rga_fall2018": ((0, 0, 1, 0, 1, 0), ("na", "na", "C4F10", "na", "N2", "na")),
    "rgb_spring2019": ((0, 0, 1, 0, 1, 0), ("na", "na", "C4F10", "na", "C4F10", "na")),
    "rgb_spring2020": ((0, 0, 1, 0, 1, 0), ("na", "na", "C4F10", "na", "C4F10", "na")),
    "rgm_fall2021_H": ((0, 1, 1, 0, 1, 1), ("na", "N2", "N2", "na", "N2", "N2")),
}

MIRROR_SURFACE = "ltcc_AlMgF2"

CAD_FRAME_SOURCES = {
    "backwall": ("G4_Al", "ccccdd", "0*mm, 0*mm, -699.3*mm", "180*deg, 0*deg, 30*deg"),
    "rightwall": ("G4_Al", "ccddcc", "0*mm, 0*mm, -699.3*mm", "180*deg, 0*deg, 30*deg"),
    "leftwall": ("G4_Al", "ccddee", "0*mm, 0*mm, -699.3*mm", "180*deg, 0*deg, 30*deg"),
    "nose": ("ltcc_nose", "cc8844", "0*mm, 0*mm, -699.3*mm", "180*deg, 0*deg, 90*deg"),
}

WINSTON_SOURCE_PLACEMENTS = {(3, "right", 1), (3, "right", 11), (3, "right", 13)}


def fstr(value):
    """Format a float the way perl stringifies numbers (%.15g)."""
    formatted = f"{float(value):.15g}"
    return "0" if formatted == "-0" else formatted


def perl_deg(value):
    """math.pm deg(): value*180.0/pi with the same operation order as perl."""
    return value * 180.0 / math.pi


def new_volume(name, mother="root"):
    volume = GVolume(name)
    volume.mother = mother
    volume.g4placement_type = "passive"
    return volume


def component_volume(name, mother="root"):
    volume = new_volume(name, mother)
    volume.material = "Component"
    return volume


def operation(volume, opr, parameters="0"):
    """Mark volume as the GEMC2 `Operation: a - b` boolean of two components."""
    volume.solidsOpr = opr
    volume.parameters = parameters
    return volume


def build_ltcc(configuration):
    """Publish all LTCC native volumes for the variation selected in configuration."""
    variation = configuration.variation
    presence, gas = SECTOR_CONFIG[variation]
    pars = load_parameters()

    build_ltcc_box(configuration, presence, gas)
    build_cyl_mirrors(configuration, pars, presence)
    build_hyp_mirrors(configuration, pars, presence, gas)
    build_ell_mirrors(configuration, pars, presence, gas)
    build_pmts(configuration, pars, presence)
    build_shields(configuration, pars, presence)


# ---------------------------------------------------------------------------
# ltccBox.pl — sector gas mother, one identical G4Trap wedge per sector
# ---------------------------------------------------------------------------
# GEMC2 placed a tilted G4Trap inside each unrotated sector mother by intersecting it with a large box.
# Keep that boolean-placement idiom so the existing daughter coordinates remain in the sector frame, but
# fit the trap to the native and CAD content rather than the larger DC-to-PCAL envelope.
def build_ltcc_box(configuration, presence, gas):
    # Coordinates are in the sector frame: x is azimuthal, y radial and z along the beam. The asymmetric
    # y half-lengths closely follow the LTCC outline, while 680 mm of normal half-depth contains the final
    # native mirror segments and the sector-3 CAD frame. The x dimensions are derived from a 29.9 deg
    # sector half-angle; deriving all four together keeps the G4Trap side faces exactly planar.
    half_z = 680.0
    half_y_minus_z = 1930.0
    half_y_plus_z = 1500.0
    center_y = 1800.0
    center_z = 3900.0
    tilt = 25.0
    sector_half_angle = 29.9

    tilt_rad = math.radians(tilt)
    sector_half_angle_rad = math.radians(sector_half_angle)
    wedge_tangent = math.tan(sector_half_angle_rad)
    side_slope = math.cos(tilt_rad) * wedge_tangent
    radial_minus_z = center_y + math.sin(tilt_rad) * half_z
    radial_plus_z = center_y - math.sin(tilt_rad) * half_z
    dx1 = radial_minus_z * wedge_tangent - half_y_minus_z * side_slope
    dx2 = radial_minus_z * wedge_tangent + half_y_minus_z * side_slope
    dx3 = radial_plus_z * wedge_tangent - half_y_plus_z * side_slope
    dx4 = radial_plus_z * wedge_tangent + half_y_plus_z * side_slope

    trap = component_volume("ltccTrap")
    trap.description = "Light Threshold Cerenkov Counter sector"
    trap.color = "110088"
    trap.solid = "G4Trap"
    trap.parameters = (
        f"{fstr(half_z)}*mm, 0*deg, 0*deg, {fstr(half_y_minus_z)}*mm, "
        f"{fstr(dx1)}*mm, {fstr(dx2)}*mm, 0*deg, {fstr(half_y_plus_z)}*mm, "
        f"{fstr(dx3)}*mm, {fstr(dx4)}*mm, 0*deg"
    )
    trap.position = f"0*mm, {fstr(center_y)}*mm, {fstr(center_z)}*mm"
    trap.rotations = [f"{fstr(tilt)}*deg, 180*deg, 0*deg"]
    trap.publish(configuration)

    big_box = component_volume("ltcc_big_box")
    big_box.description = "Light Threshold Cerenkov Counter Box at the origin"
    big_box.solid = "G4Box"
    big_box.parameters = "3*m, 5*m, 6*m"
    big_box.publish(configuration)

    for sector in SECTORS:
        if not presence[sector - 1]:
            continue
        # this does not include the 5 cm shift for the forward carriage we observed
        c6toc12z = 1973
        rot_phi = 90 - (sector - 1) * 60
        sector_volume = new_volume(f"ltccS{sector}")
        sector_volume.description = f"ltcc sector {sector}"
        sector_volume.position = f"0*mm, 0*mm, {c6toc12z}*mm"
        sector_volume.rotations = [f"0*deg, 0*deg, {rot_phi}*deg"]
        sector_volume.color = "110088"
        sector_volume.visible = 0
        sector_volume.material = gas[sector - 1]
        operation(sector_volume, "ltcc_big_box * ltccTrap").publish(configuration)


# ---------------------------------------------------------------------------
# cyl_mirrors.pl — cylindrical mirrors in front of the Winston cones
# ---------------------------------------------------------------------------
def build_cyl_mirrors(configuration, pars, presence):
    for n in range(1, NMIRRORS):  # perl: if ($n < $endN)
        s = n  # parameters are indexed by segment
        router = pars[f"ltcc.cyl.s{s}_router"]
        cyl_inner = fstr(float(router) - 0.1)  # mirror thickness is 1 mm
        cyl_ang = fstr(90 + float(pars[f"ltcc.shield.s{s}_zangle"]))
        segtheta = 90 - float(pars[f"ltcc.s{s}_theta"])
        segphi_cyl = fstr(-90 - segtheta)
        tilt = pars[f"ltcc.wc.s{s}_angle"]

        for sector in SECTORS:
            if not presence[sector - 1]:
                continue
            # unlike the pmts, the left cylindrical mirror carries the -tilt
            for side, tilt_sign in (("right", ""), ("left", "-")):
                mirror = new_volume(f"cyl_mirrors_s{sector}{side}_{n}", f"ltccS{sector}")
                mirror.description = f"cyl mirrors {side} {n}"
                suffix = "R" if side == "right" else "L"
                mirror.position = (
                    f"{pars[f'ltcc.mirror.s{s}_x{suffix}']}*cm, "
                    f"{pars[f'ltcc.mirror.s{s}_y{suffix}']}*cm, "
                    f"{pars[f'ltcc.mirror.s{s}_z{suffix}']}*cm"
                )
                mirror_tilt = tilt_sign + tilt
                cyl_tilt = pars[f"ltcc.cyl.s{s}_{'rightAngle' if side == 'right' else 'leftAngle'}"]
                mirror.rotations = [f"{segphi_cyl}*deg, {mirror_tilt}*deg, {cyl_tilt}*deg"]
                mirror.color = "aaffff"
                mirror.solid = "G4Tubs"
                mirror.parameters = f"{cyl_inner}*cm, {router}*cm, 3*cm, 0*deg, {cyl_ang}*deg"
                mirror.material = "G4_Al"
                mirror.style = 1
                mirror.mirror = MIRROR_SURFACE
                mirror.publish(configuration)


# ---------------------------------------------------------------------------
# hyp_mirrors.pl — hyperbolic mirrors approximated by G4Polyhedra (Pgon)
# ---------------------------------------------------------------------------
def hyp_y(pars, x, s):
    """calc_yp: y of the hyperbola branch at x for segment s (1-based)."""
    p1 = float(pars[f"ltcc.hypars.s{s}.p0"])
    p2 = float(pars[f"ltcc.hypars.s{s}.p1"])
    p3 = float(pars[f"ltcc.hypars.s{s}.p2"])
    p4 = float(pars[f"ltcc.hypars.s{s}.p3"])
    p5 = float(pars[f"ltcc.hypars.s{s}.p4"])

    a = p2
    b = p3 * x + p5
    c = 1 + p1 * x * x + p4 * x
    return (-b - math.sqrt(b * b - 4 * a * c)) / (2 * a)


def build_hyp_mirrors(configuration, pars, presence, gas):
    for n in range(1, NMIRRORS + 1):
        x21 = float(pars[f"ltcc.hy.s{n}_x21"])
        y21 = float(pars[f"ltcc.hy.s{n}_y21"])
        hp_min = pars[f"ltcc.hy.s{n}_xmin"]
        m_width = float(pars[f"ltcc.hy.s{n}_width"])
        segtheta = 90 - float(pars[f"ltcc.s{n}_theta"])

        # the hyperbolic mirrors are pgon with a number of sides dependent on
        # their dimensions
        nsides = int((x21 - float(hp_min)) / 3) + 1
        dx = (x21 - float(hp_min)) / nsides
        xpos = [side * dx for side in range(nsides)]
        ypos1 = [hyp_y(pars, float(hp_min) + side * dx, n) for side in range(nsides)]
        miny = min(min(ypos1), 9999)

        # We want to add thickness to the minimum
        ypossub = -m_width - 2
        suby = miny + ypossub
        ypos0 = ypossub + y21
        ypos1 = [y - suby for y in ypos1]
        ypos2 = [y + 1 for y in ypos1]  # mirror depth thickness

        dimensions = f"45*deg, 90*deg, 1*counts, {nsides}*counts"
        for value in ypos1 + ypos2 + xpos:
            dimensions += f", {fstr(value)}*cm"

        # hyperbolic shape (full)
        hyperbolic = component_volume(f"hyperbolic_{n}")
        hyperbolic.description = f"LTCC Hyperbolic full shape {n}"
        hyperbolic.solid = "G4Polyhedra"
        hyperbolic.parameters = dimensions
        hyperbolic.publish(configuration)

        # Right and left boxes to subtract
        box_d = 100
        for side, sign in (("right", 1), ("left", -1)):
            sbox = component_volume(f"{side}_sbox_{n}")
            sbox.description = f"LTCC Hyperbolic mirror {side} subtract box {n}"
            sbox.position = f"{fstr(sign * (m_width + box_d))}*cm, 0*mm, 0*cm"
            sbox.solid = "G4Box"
            sbox.parameters = f"{box_d}*cm, {box_d}*cm, {box_d}*cm"
            sbox.publish(configuration)

        # Subtracting left box
        rbox = component_volume(f"hyperbolix_rbox_{n}")
        rbox.description = f"LTCC Hyperbolic mirror right minus right box {n}"
        operation(rbox, f"hyperbolic_{n} - left_sbox_{n}").publish(configuration)

        # Building the box that contains the mirrors (left and right)
        # Starts 1mm above x11
        segment_box_length = x21 + 0.1
        segment_box_thickness = m_width + 0.1
        yshift = 22  # Should be enough to encompass all mirrrors
        segment_box_height = ypos0 + yshift
        segment_box = component_volume(f"segment_hyp_box_{n}")
        segment_box.description = f"Light Threshold Cerenkov Counter HYP Segment Box {n}"
        segment_box.color = "880011"
        segment_box.solid = "G4Box"
        segment_box.parameters = (
            f"{fstr(segment_box_length)}*cm, {fstr(segment_box_height)}*cm, "
            f"{fstr(segment_box_thickness)}*cm"
        )
        segment_box.publish(configuration)

        # Box to subract from segment box. Starts at YPOS0
        subtract_box = component_volume(f"segment_hyp_subtract_box_{n}")
        subtract_box.description = f"Light Threshold Cerenkov Counter Segment Box to Subtract {n}"
        subtract_box.position = f"0*cm, -{yshift}*cm, 0*mm"
        subtract_box.color = "1100ff"
        subtract_box.solid = "G4Box"
        subtract_box.parameters = (
            f"{fstr(segment_box_length + 0.2)}*cm, {fstr(segment_box_height)}*cm, "
            f"{fstr(segment_box_thickness + 0.2)}*cm"
        )
        subtract_box.publish(configuration)

        for sector in SECTORS:
            if not presence[sector - 1]:
                continue

            for side, rot_sign, pos_sign in (("right", "-", ""), ("left", "", "-")):
                mirror = new_volume(
                    f"hyp_mirror_s{sector}_{side}_{n}", f"segment_hyp_s{sector}_{n}"
                )
                mirror.description = f"LTCC Hyperbolic mirror right {n}"
                mirror.position = f"{pos_sign}{hp_min}*cm, {fstr(ypos0)}*cm, 0*cm"
                mirror.rotations = [f"0*deg, {rot_sign}90*deg, 0*deg"]
                mirror.color = "aaffff"
                mirror.material = "G4_Al"
                mirror.style = 1
                mirror.mirror = MIRROR_SURFACE
                operation(mirror, f"hyperbolix_rbox_{n} - right_sbox_{n}").publish(configuration)

            segment = new_volume(f"segment_hyp_s{sector}_{n}", f"ltccS{sector}")
            segment.description = f"Light Threshold Cerenkov Counter HYP segment {n}"
            segment.rotations = [f"-{fstr(segtheta)}*deg, 0*deg, 0*deg"]
            segment.color = "00ff11"
            segment.material = gas[sector - 1]
            segment.visible = 0
            if n == 15:
                segment.position = "0*cm, 5*cm, 10*cm"
            if n == 16:
                segment.position = "0*cm, 10*cm, 15*cm"
            if n == 17:
                segment.position = "0*cm, 15*cm, 20*cm"
            if n == 18:
                segment.position = "0*cm, 20*cm, 25*cm"
            operation(
                segment, f"segment_hyp_box_{n} - segment_hyp_subtract_box_{n}"
            ).publish(configuration)


# ---------------------------------------------------------------------------
# ell_mirrors.pl — elliptical mirrors cut from elliptical tube shells
# ---------------------------------------------------------------------------
def ell_segment_pars(pars, n):
    """Return the derived ellipse quantities for segment n (1-based)."""
    a = float(pars[f"ltcc.elpars.s{n}.p0"])
    b = float(pars[f"ltcc.elpars.s{n}.p1"])
    c = float(pars[f"ltcc.elpars.s{n}.p2"])
    d = float(pars[f"ltcc.elpars.s{n}.p3"])
    f = float(pars[f"ltcc.elpars.s{n}.p4"])

    # ellipse center
    centerx = (2.0 * b * d - c * f) / (c * c - 4.0 * a * b)
    centery = (2.0 * a * f - c * d) / (c * c - 4.0 * a * b)

    # ellipse tilt
    alpha = perl_deg(0.5 * math.pi + 0.5 * math.atan(c / (a - b)))

    # pd: parameters after shift; notation consistent with Alex Vlassov
    atcenter = (
        a * centerx * centerx + b * centery * centery
        + c * centerx * centery + d * centerx + f * centery + 1.0
    )
    pd1 = a / atcenter
    pd2 = b / atcenter
    pd3 = c / atcenter
    pd4 = (d + c * centery + 2 * a * centerx) / atcenter
    pd5 = (f + c * centerx + 2 * b * centery) / atcenter

    # pc: parameters after rotation
    cs = math.cos(-alpha * math.pi / 180.0)
    sn = math.sin(-alpha * math.pi / 180.0)
    pc1 = pd1 * cs * cs + pd2 * sn * sn - pd3 * sn * cs
    pc2 = pd1 * sn * sn + pd2 * cs * cs + pd3 * sn * cs
    pc4 = pd4 * cs - pd5 * sn
    pc5 = pd5 * cs + pd4 * sn

    # calculating semi-axis, following Alex formalism
    skobka = 0.25 * pc4 * pc4 / pc1 + 0.25 * pc5 * pc5 / pc2 - 1.0
    axisa = math.sqrt(skobka / pc1)
    axisb = math.sqrt(skobka / pc2)

    # span angles for the ellipse: angle between the end (start) of the segment
    # and the vertical line passing through the center of the ellipse
    x12 = float(pars[f"ltcc.el.s{n}_x12"])
    y12 = float(pars[f"ltcc.el.s{n}_y12"])
    xloc2 = x12 - centerx
    yloc2 = y12 - centery
    end_tocangle = 90 - math.atan(yloc2 / xloc2) * 180.0 / math.pi

    y11 = float(pars[f"ltcc.el.s{n}_y11"])
    xloc1 = 0 - centerx
    yloc1 = y11 - centery
    if centerx < 0:
        sta_tocangle = -90 + math.atan(yloc1 / xloc1) * 180.0 / math.pi
    else:
        sta_tocangle = 90 + math.atan(yloc1 / xloc1) * 180.0 / math.pi

    return {
        "centerx": centerx,
        "centery": centery,
        "alpha": alpha,
        "axisa": axisa,
        "axisb": axisb,
        "x12": x12,
        "y12": y12,
        "y11": y11,
        "end_tocangle": end_tocangle,
        "sta_tocangle": sta_tocangle,
        "segtheta": 90 - float(pars[f"ltcc.s{n}_theta"]),
        "width": float(pars[f"ltcc.el.s{n}_width"]),
    }


def build_ell_mirrors(configuration, pars, presence, gas):
    ell = {n: ell_segment_pars(pars, n) for n in range(1, NMIRRORS + 1)}
    mirrors_thickness = 1  # mirrors are 1 cm thick

    # Building the boxes that contain the mirrors (both left and right)
    for n in range(1, NMIRRORS + 1):
        e = ell[n]
        # Starts 1mm above x11
        segment_box_length = e["x12"] + 0.5
        segment_box_thickness = e["width"] + 0.1
        segment_box_height = e["y11"] + 5  # Harcoded 5 mm to add to box
        if e["y12"] > e["y11"]:
            segment_box_height = e["y12"] + 5

        segment_box = component_volume(f"segment_ell_box_{n}")
        segment_box.description = f"Light Threshold Cerenkov Counter Segment Box {n}"
        segment_box.solid = "G4Box"
        segment_box.parameters = (
            f"{fstr(segment_box_length)}*cm, {fstr(segment_box_height)}*cm, "
            f"{fstr(segment_box_thickness)}*cm"
        )
        segment_box.publish(configuration)

        # Box to subract from segment box.
        # Starts 1mm below and to the right of end point x12, y12
        yshift = segment_box_height - e["y12"] + 2.0
        if e["y12"] > e["y11"]:
            yshift = segment_box_height - e["y11"] + 2.0

        subtract_box = component_volume(f"segment_ell_subtract_box_{n}")
        subtract_box.description = f"Light Threshold Cerenkov Counter Segment Box to Subtract {n}"
        subtract_box.position = f"0*cm, -{fstr(yshift)}*cm, 0*mm"
        subtract_box.solid = "G4Box"
        subtract_box.parameters = (
            f"{fstr(segment_box_length + 0.2)}*cm, {fstr(segment_box_height)}*cm, "
            f"{fstr(segment_box_thickness + 0.2)}*cm"
        )
        subtract_box.publish(configuration)

        for sector in SECTORS:
            if not presence[sector - 1]:
                continue
            # The subtraction is done so that the container has the same
            # coordinates as clas center
            segment = new_volume(f"segment_ell_s{sector}_{n}", f"ltccS{sector}")
            segment.description = (
                f"Light Threshold Cerenkov Counter ELL sector {sector} segment {n}"
            )
            segment.rotations = [f"-{fstr(e['segtheta'])}*deg, 0*deg, 0*deg"]
            segment.material = gas[sector - 1]
            segment.visible = 0
            if n == 16:
                segment.position = "0*cm, 5*cm, 10*cm"
            if n == 17:
                segment.position = "0*cm, 10*cm, 15*cm"
            if n == 18:
                segment.position = "0*cm, 15*cm, 20*cm"
            operation(
                segment, f"segment_ell_box_{n} - segment_ell_subtract_box_{n}"
            ).publish(configuration)

    # builds the complete elliptical shells, to be cut by cheese forms later
    for n in range(1, NMIRRORS + 1):
        e = ell[n]
        outer = component_volume(f"el_outer_shell_{n}")
        outer.description = f"Light Threshold Cerenkov Counter Mirror Outside {n}"
        outer.solid = "G4EllipticalTube"
        outer.parameters = f"{fstr(e['axisa'])}*cm, {fstr(e['axisb'])}*cm, {fstr(e['width'])}*cm"
        outer.publish(configuration)

        # making the inner 1 cm bigger so the subtraction is guaranteed
        inner = component_volume(f"el_inner_shell_{n}")
        inner.description = f"Light Threshold Cerenkov Counter Mirror Inside {n}"
        inner.solid = "G4EllipticalTube"
        inner.parameters = (
            f"{fstr(e['axisa'] - mirrors_thickness)}*cm, "
            f"{fstr(e['axisb'] - mirrors_thickness)}*cm, {fstr(e['width'] + 1.0)}*cm"
        )
        inner.publish(configuration)

        # The segment sits on the ellipse top half. The right ellipse is rotated
        # by 180 - alpha because the rotation angle starts from the positive x
        # axis; the left one is the x-symmetric of the right one.
        for side, cntx, angle in (
            ("right", e["centerx"], 180 - e["alpha"]),
            ("left", -e["centerx"], e["alpha"]),
        ):
            tube = component_volume(f"ellipse_tube_{side}_{n}")
            tube.description = f"Light Threshold Cerenkov Counter Mirror Frame {n}"
            tube.position = f"{fstr(cntx)}*cm, {fstr(e['centery'])}*cm, 0*mm"
            tube.rotations = [f"0*deg, 0*deg, {fstr(angle)}*deg"]
            operation(tube, f"el_outer_shell_{n} - el_inner_shell_{n}").publish(configuration)

    # mirrors are cut from the ell shells with the cheese forms
    for n in range(1, NMIRRORS + 1):
        e = ell[n]
        newcenterx = e["centerx"] + 0.2
        ralpha = 180 - e["alpha"]
        lalpha = e["alpha"]
        tubespan = 360 - (e["end_tocangle"] + e["sta_tocangle"])
        starttheta_r = 90 + e["sta_tocangle"]
        starttheta_l = 90 + e["end_tocangle"]

        for side, angle, starttheta, color in (
            ("right", ralpha, starttheta_r, "110088"),
            ("left", lalpha, starttheta_l, "880011"),
        ):
            span_tube = component_volume(f"span_tube_{side}_{n}")
            span_tube.description = (
                "Light Threshold Cerenkov Counter Mirror Tube with Max Theta - "
                f"{side.upper()} segment {n}"
            )
            span_tube.rotations = [f"0*deg, 0*deg, -{fstr(angle)}*deg"]
            span_tube.color = color
            span_tube.solid = "G4Tubs"
            span_tube.parameters = (
                f"0*m, 5*m, 0.6*m, {fstr(starttheta)}*deg, {fstr(tubespan)}*deg"
            )
            span_tube.style = 1
            span_tube.publish(configuration)

        for sector in SECTORS:
            if not presence[sector - 1]:
                continue
            # Adding 0.1 deg to avoid overlaps
            for side, cntx, angle in (
                ("right", newcenterx, ralpha + 0.01),
                ("left", -newcenterx, lalpha - 0.01),
            ):
                mirror = new_volume(
                    f"el_mir_s{sector}_{side}_{n}", f"segment_ell_s{sector}_{n}"
                )
                mirror.description = f"LTCC {side.capitalize()} Mirror Sector {sector} Segment {n}"
                mirror.position = f"{fstr(cntx)}*cm, {fstr(e['centery'])}*cm, 0*mm"
                mirror.rotations = [f"0*deg, 0*deg, {fstr(angle)}*deg"]
                mirror.color = "aaffff"
                mirror.material = "G4_AIR_Optical"
                mirror.style = 1
                mirror.mirror = MIRROR_SURFACE
                operation(
                    mirror, f"ellipse_tube_{side}_{n} - span_tube_{side}_{n}", "0*m"
                ).publish(configuration)


# ---------------------------------------------------------------------------
# pmts.pl — sensitive PMTs
# ---------------------------------------------------------------------------
def build_pmts(configuration, pars, presence):
    for n in range(1, NMIRRORS + 1):
        radius = pars[f"ltcc.pmt.s{n}_radius"]
        tilt = pars[f"ltcc.wc.s{n}_angle"]
        segtheta = 90 - float(pars[f"ltcc.s{n}_theta"])
        segphi = fstr(90 - segtheta)
        position = (
            f"{pars[f'ltcc.pmt.s{n}_x']}*cm, {pars[f'ltcc.pmt.s{n}_y']}*cm, "
            f"{pars[f'ltcc.pmt.s{n}_z']}*cm"
        )

        for sector in SECTORS:
            if not presence[sector - 1]:
                continue
            for side, side_id, pos_sign, tilt_sign in (
                ("right", 1, "", "-"),
                ("left", 2, "-", ""),
            ):
                pmt = new_volume(f"pmt_s{sector}{side}_{n}", f"ltccS{sector}")
                pmt.description = f"PMT {side} {n}"
                pmt.position = pos_sign + position if pos_sign else position
                pmt.rotations = [f"{segphi}*deg, {tilt_sign}{tilt}*deg, 0*deg"]
                pmt.color = "800000"
                pmt.solid = "G4Tubs"
                pmt.parameters = f"0*cm, {radius}*cm, 0.1*cm, 0*deg, 360*deg"
                pmt.material = "LTCCPMTGlass"
                pmt.style = 1
                pmt.digitization = "ltcc"
                pmt.set_identifier("sector", sector, "side", side_id, "segment", n)
                pmt.publish(configuration)


# ---------------------------------------------------------------------------
# shields.pl — 5 mm iron shields covering the outer face of the Winston cones
# ---------------------------------------------------------------------------
def build_shields(configuration, pars, presence):
    for n in range(1, NMIRRORS):  # perl: if ($n < $endN)
        tilt = pars[f"ltcc.wc.s{n}_angle"]
        shield_dx = pars[f"ltcc.shield.s{n}_dx"]
        shield_dy = pars[f"ltcc.shield.s{n}_dy"]
        shield_dz = pars[f"ltcc.shield.s{n}_dz"]
        shield_tilt = pars[f"ltcc.shield.s{n}_zangle"]
        segtheta = 90 - float(pars[f"ltcc.s{n}_theta"])
        segphi = fstr(90 - segtheta)
        # To make shields with 5 mm thickness, boxes 1 mm smaller are subtracted
        # from the original ones
        sub_dx = fstr(float(shield_dx) - 0.5)
        sub_dy = fstr(float(shield_dy) - 0.5)
        sub_dz = fstr(float(shield_dz) + 0.5)

        for sector in SECTORS:
            if not presence[sector - 1]:
                continue
            # Shield dimensions are not real dimensions: their sizes are
            # decreased to avoid overlaps with other geometries and neighbor
            # shields
            for side, tilt_sign, ztilt_sign in (("right", "-", ""), ("left", "", "-")):
                shield = component_volume(f"shield_s{sector}{side}_{n}", f"ltccS{sector}")
                shield.description = f"shield {side} {n}"
                shield.position = "0*cm, 0*cm, 0*cm"
                shield.rotations = ["0*deg, 0*deg, 0*deg"]
                shield.color = "000000"
                shield.solid = "G4Box"
                shield.parameters = f"{shield_dx}*cm, {shield_dy}*cm, {shield_dz}*cm"
                shield.publish(configuration)

                subtraction = component_volume(
                    f"subtraction_shield_s{sector}{side}_{n}", f"ltccS{sector}"
                )
                subtraction.description = f"Subtraction shield {side} {n}"
                subtraction.position = "0*cm, 0*cm, 0*cm"
                subtraction.rotations = ["0*deg, 0*deg, 0*deg"]
                subtraction.color = "000000"
                subtraction.solid = "G4Box"
                subtraction.parameters = f"{sub_dx}*cm, {sub_dy}*cm, {sub_dz}*cm"
                subtraction.publish(configuration)

                # GEMC2 quirk preserved: the right combined shield has no
                # underscore before the segment number
                final_name = (
                    f"final_shield_s{sector}right{n}"
                    if side == "right"
                    else f"final_shield_s{sector}left_{n}"
                )
                suffix = "R" if side == "right" else "L"
                final_shield = new_volume(final_name, f"ltccS{sector}")
                final_shield.description = f"combined shield {side} {n}"
                final_shield.position = (
                    f"{pars[f'ltcc.shield.s{n}_x{suffix}']}*cm, "
                    f"{pars[f'ltcc.shield.s{n}_y{suffix}']}*cm, "
                    f"{pars[f'ltcc.shield.s{n}_z{suffix}']}*cm"
                )
                final_shield.rotations = [
                    f"{segphi}*deg, {tilt_sign}{tilt}*deg, {ztilt_sign}{shield_tilt}*deg"
                ]
                final_shield.color = "202020"
                final_shield.material = "G4_Fe"
                final_shield.style = 1
                operation(
                    final_shield,
                    f"shield_s{sector}{side}_{n} - subtraction_shield_s{sector}{side}_{n}",
                ).publish(configuration)


# ---------------------------------------------------------------------------
# cones.pl / ltcc_frame.pl — copies of the sector-3 CAD mesh sources
# ---------------------------------------------------------------------------
def build_cad_copies(configuration):
    """Publish frame and Winston-cone copyOf placements for every present sector."""
    presence, _ = SECTOR_CONFIG[configuration.variation]
    pars = load_parameters()

    build_frame_copies(configuration, presence)
    build_winston_cone_copies(configuration, pars, presence)


def build_frame_copies(configuration, presence):
    """Reuse each sector-3 frame/nose mesh at the same local placement in the other sectors."""
    for sector in SECTORS:
        if sector == 3 or not presence[sector - 1]:
            continue
        for source, (material, color, position, rotation) in CAD_FRAME_SOURCES.items():
            frame = new_volume(f"{source}_s{sector}", f"ltccS{sector}")
            frame.description = f"LTCC sector {sector} {source} CAD copy"
            frame.position = position
            frame.rotations = [rotation]
            frame.material = material
            frame.color = color
            frame.copyOf = source
            frame.publish(configuration)


def build_winston_cone_copies(configuration, pars, presence):
    """Port cones.pl placements while reusing the three small/medium/large CAD meshes."""
    for n in range(1, NMIRRORS):  # clas12Tags omits cone segment 18
        if n < 11:
            source = "WC_S"
            material = "G4_Cu"
        elif n < 13:
            source = "WC_M"
            material = "G4_PLASTIC_SC_VINYLTOLUENE"
        else:
            source = "WC_L"
            material = "G4_Cu"

        segtheta = 90 - float(pars[f"ltcc.s{n}_theta"])
        segphi = fstr(90 - segtheta)
        tilt = pars[f"ltcc.wc.s{n}_angle"]
        shield_tilt = pars[f"ltcc.shield.s{n}_zangle"]

        for sector in SECTORS:
            if not presence[sector - 1]:
                continue
            for side, suffix, tilt_sign, shield_sign in (
                ("right", "R", "-", ""),
                ("left", "L", "", "-"),
            ):
                if (sector, side, n) in WINSTON_SOURCE_PLACEMENTS:
                    continue

                cone = new_volume(f"cone_s{sector}{side}_{n}", f"ltccS{sector}")
                cone.description = f"cone {side} {n}"
                cone.position = (
                    f"{pars[f'ltcc.wc.s{n}_x{suffix}']}*cm, "
                    f"{pars[f'ltcc.wc.s{n}_y{suffix}']}*cm, "
                    f"{pars[f'ltcc.wc.s{n}_z{suffix}']}*cm"
                )
                cone.rotations = [
                    f"{segphi}*deg, {tilt_sign}{tilt}*deg, {shield_sign}{shield_tilt}*deg"
                ]
                cone.material = material
                cone.color = "aa9999"
                cone.copyOf = source
                cone.mirror = MIRROR_SURFACE
                cone.publish(configuration)
