name: Dawn Screenshot

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:
  pull_request:
    types:
      # only run workflow when a commit is pushed to a PR branch
      # instead of running for all other PR events
      - synchronize

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix:  ${{ steps.set-matrix.outputs.matrix }}
      jobtype: ${{ steps.set-matrix.outputs.jobtype }}
    steps:
      - name: Check changed files
        uses: actions/checkout@main
      - id: set-matrix
        run: |
          if [ $GITHUB_BASE_REF ]; then
            BASE_REF=no
          else
            BASE_REF=$GITHUB_BASE_REF
          fi
          export JSON=$(    ./ci/whatToTest.sh -b $BASE_REF -c $GITHUB_SHA -g $GITHUB_BEFORE )
          export JOBTYPE=$( echo $JSON | grep irrelevant | wc -l )
          echo generate-matrix: $JSON, ignore:  $JOBTYPE
          echo "::set-output name=matrix::$(  echo "$JSON"    | tr -d '\n' )"
          echo "::set-output name=jobtype::$( echo "$JOBTYPE" | tr -d '\n' )"
    env:
      GITHUB_BEFORE: ${{ github.event.before }}


  # Run jcard in tests directory
  runTests:
    needs: generate-matrix
    if: needs.generate-matrix.outputs.jobtype == '0'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:3.0-clas12
    name: Dawn Screenshot ${{ matrix.detector }}
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Run Dawn
        run: |
          ./ci/tests.sh -s ${{ matrix.detector }} -d
      - name: Archive PDFs
        uses: actions/upload-artifact@v3
        with:
          name: Archive Dawn Screenshots
          path: screenshots
      - name: Commit PDFs
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git diff
          git add screenshot
          #git commit -m 'Re-build package plot' || echo "No changes to commit"
          #git push origin || echo "No changes to commit"


