# This is a basic workflow to help you get started with Actions

name: clas12-system

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:
  pull_request:
    types:
      # only run workflow when a commit is pushed to a PR branch
      # instead of running for all other PR events
      - synchronize

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Build the geometry and plugins, install them in systemsTxtDB
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:3.0-clas12
    name: Build ${{ matrix.detector }}
    strategy:
      fail-fast: false
      matrix:
        detector:
          - ft/ft_cal
          - ftof

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build geo
        run: |
          ./ci/build.sh -s ${{ matrix.detector }}

  # Build the geometry and plugins, runs overlaps test
  overlap:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:3.0-clas12
    name: Overlap Test ${{ matrix.detector }}
    strategy:
      fail-fast: false
      matrix:
        detector:
          - ft/ft_cal

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Overlaps test
        run: |
          ./ci/tests.sh -s ${{ matrix.detector }} -o
